# 5 Resampling Methods

- Involve repeatedly drawing samples from a training set and refitting a model of interest on each sample in order to obtain additional information about the fitted model.
- can be computationally expensive
- This chapter discusses two of the most commonly used resampling methods, *cross-validation* and *bootstrap*

For example, cross-validation can be used to estimate the test error associated with a given statistical learning method in order to evaluate its performance, or to select the appropriate level of flexibility


    The process of evaluating a model's performance is known as *model assessment* whereas the process of selecting the proper level of flexibility for a model is known as *model selection*

The bootstrap is used in several contexts, most commonly to provide a measure of accuracy of a parameter estimate or of a given statistical learning method.

## 5.1 Cross-validation
In statistical learning, we focus on the test error. The test error can be easily calculated if a designated test set is available. Unfortuantely, this is usually not the case.

In the absence of a very large designated test set that can be used to directly estimate the test error rate, a number of techniques can be used to estimate this quantity using the available training data. 
- Some methods make a mathematical adjustment to the training error rate in order to estimate the test error rate. Such approacheds are discussed in Chapter 6
- In this section, we instead consider a class of methods that estimate the test error rate by *holding out* a subset of the training observations from the fitting process and then applying the statistical learning method to those held out observations.

### 5.1.1 The Validation Set Approach

Suppose that we would like to estimate the test error assoiated with fitting a particular statistical learning method on a set of observations.

The validateion set approach is a very simple strategy, which involves randomly dividing the available set of observations into two partes, a *training set* and a *validation set*

Problems
- The validation estimate of the test error rate can be highly variable, depending on which observations are included in the training set.

- In the validation approach, only a subset of the observations --those that are included in the training set rather than in the validation set-- are used to fit the model. THis can lead to overestimation of the test error rate. 

.

    We will present *cross-validation* , a refinement of the validation set approach that addresses these two issues

### 5.1.2 Leave-One-Out Cross Validation

*Leave-one-out-cross-validation* (LOOCV) is closely related to the validation set approach but it attemps to address that method's drawbacks

In LOOCV, only one observation is used for the validation set, and the remaining observations make up the training set.
Then the estimate for the test MSE is the average of the n test error estimates:

$$
CV_{(n)}=\frac{1}{n}\sum_{i=1}^nMSE_i
$$

#### Advantages over the validation set approach of LOOCV:
1. Has far less bias due to high number of observations in training sets
2. Tends not to overestimate the test error rate as much as the validation set approach
3. The validation approach will yield different results when applied repeatedly due to randomness in the training/validation set splits, performing LOOCV multiple times will always tield the same results
#### Caveats
1. expensive to implement since the model has to be fit n times

#### Shortcuts for least squares linear or polynomial regression

$$
CV_{(n)}=\frac{1}{n}\sum_{i=1}^n(\frac{y_i=\hat{y}_i}{1-h_i})^2
$$

where $h_i$ is the leverage



### 5.1.3 k-fold Cross-Validation
An alternative to LOOCV is k-fold CV. 
#### Steps
1. This approach involves randomly dividing the set of observations into k groups, or *folds*, of approximately equal size. 
2. The first fold is treated as a validation set, and the method is fit on the remaining $k-1$ folds
3. The mean squared error, $MSE_1$, is repeated k times; each time, a different group of observations is treated as a validation set
4. The k-fold CV estimate is computed by averaging these values
$$
CV_{(k)}=\frac{1}{k}\sum_{i=1}^kMSE_i
$$

### Comments
 There are some variability in the CV estimates as a result of the variability in how the observations are divided into ten folds but this variability is typically much lower than the variability in the test error estimates that results from the validation set approach

When we perform cross-validation, our goal might be to determine how well a given statistical learning procedure can be expected to perform on independent data.

At other times we are interested only in the location of the minimum point in the estimated test MSE curve.
- This is because we might be performing cross-validation on a number of statistical learning methods, or on a single method using different levels of flexibility, in order to identify the method that results in the lowest test error.
- For this purpose, the location of the minimum point in the estimated test MSE curve is important, bot the estimated test MSE

### 5.1.4 Bias-Variance Trade-Off for k-Fold Cross-Validation


We mentioned that k-fold CV with $k<n$ has a computational advantage to LOOCV

Putting this aside, a less obvious but potentially more imporant advantage of k-fold CV is that it often gives more accurate estimates of the test error rate than does LOOCV. This has to do with a bias-variance trade-off

For bias: validation set approach > k-fold CV > LOOCV because of the number of observations in the training set
For variance LOOCV > k-fold CV
- Why?
- Because LOOCV have highly correlated outputs. In contrast, in k-fold CV with $k<n$, the outputs are less correlated. Since the mean of many highly correlated quantities has higher variance than does the mean of many quantities that are not as highly correlated, the test error estimate resulting from LOOCV tends to have higher variance than does the test error estimate resulting from k-fold CV

#### reccomendation
Use k = 5 or k =10


### 5.1.5 Cross-Validation on Classification Problems
In the classification setting, the LOOCV error rate takes the form
$$
CV_{(n)}=\frac{1}{n}\sum_{i=1}^nErr_i,
$$
where $Err_i=I(y_i \neq \hat{y}_i)$

In real life, the Bayes error rate is unknown. We can use cross-validation in order to make decision on which model to use.

Note that, the training error tends to decrease as the flexibility of the model increase. In contrast, the test error displays a characteristic U-shape

## 5.2 The Bootstrap
The bootstrap is a widely applicable and extremely powerful statistical tool that can be used to quantify the uncertainty associated with a given estimator or statistical learning method.

Its power lies in the fact taht it can be easily applied to a wide range of statistical learning methods, uncluding some for which a measure of variability is other wise difficult to obtain and is not automatically output by statistical software.

### The example
1. Problem: Suppose that we wish to invest a fixed sum of money in two financial assets that yield returns of $X$ and $Y$ , respectively, where $X$ and $Y$ are random quantities. We will invest a fraction α of our money in $X$, and will invest the remaining $1 − α$ in $Y$ . Since there is variability associated with the returns on these two assets, we wish to choose α to minimize the total risk, or variance, of our investment. In other words, we want to minimize 4Var(αX + (1 − α)Y )$. 

2. 
$$
\alpha=\frac{\sigma_Y^2-\sigma_{XY}}{\sigma_X^2+\sigma_Y^2-2\sigma_{XY}}
$$

3. Generate 100 paired observations of $X$ and $Y$, and estimating $\alpha$
4. Repeated step 3 for 1000 times.
5. Calculate $mean(\hat{\alpha})$ and $Var(\hat{\alpha})$ to estimate $\alpha$ and $Var(\alpha)$

### In practice
- The procedure for estimating $Var(\hat{\alpha})$ above cannot be applied, because for real data we cannot generate new samples from the original population. 

- However, the bootstrap approach allows us to use a computer to emulate the process of obtaining new sample sets, so that we can estimate the variability of $\hat{\alpha}$

.

    Rather than repeatedly obtaining independent data sets from the population, we instead obtain distinct data sets by repeatedly sampling with replacement observations from the original data set

## 5.3 Lab: Cross-Validation and the Bootstrap


In [1]:
# Loading usual libraries
import numpy as np
import statsmodels.api as sm
from ISLP import load_data
from ISLP.models import (ModelSpec as MS,
summarize ,
poly)
from sklearn.model_selection import train_test_split

In [2]:
# new imports
 
from functools import partial
from sklearn.model_selection import \
(cross_validate , 
 KFold , 
 ShuffleSplit)
from sklearn.base import clone
from ISLP.models import sklearn_sm

### 5.3.1 Thevalidation Set Approach



In [5]:
# loading data
Auto = load_data('Auto')
Auto_train, Auto_valid = train_test_split(Auto, 
                                          test_size =196, 
                                          random_state =0)

In [6]:
# specify model
hp_mm=MS(['horsepower'])
X_train = hp_mm.fit_transform(Auto_train)
y_train = Auto_train['mpg']
model=sm.OLS(y_train,X_train)
results = model.fit()

In [7]:
X_valid = hp_mm.transform(Auto_valid)
y_valid = Auto_valid['mpg']
valid_pred = results.predict(X_valid)
np.mean((y_valid-valid_pred)**2)

23.61661706966987

In [8]:
def evalMSE(terms, response ,
    train , test):
    mm = MS(terms)
    X_train = mm.fit_transform(train) 
    y_train = train[response]
    X_test = mm.transform(test) 
    y_test = test[response]
    results = sm.OLS(y_train, X_train).fit() 
    test_pred = results.predict(X_test)
    return np.mean((y_test - test_pred)**2)

In [9]:
MSE = np.zeros(3)
for idx, degree in enumerate(range(1, 4)):
    MSE[idx] = evalMSE([poly('horsepower', degree)], 'mpg',
                       Auto_train,
                       Auto_valid)
MSE

array([23.61661707, 18.76303135, 18.79694163])

### 5.3.2 Cross-Validation
A problem in the data science worlds:
I have a function A, I need task B, so I can compute B(A(D), where D is my data.
When A and B don't naturally speak to each other, this requires the use of a *wrapper*

In [10]:
# LOOCV
hp_model = sklearn_sm(sm.OLS, MS(['horsepower']))
X, Y = Auto.drop(columns=['mpg']), Auto['mpg']
cv_results = cross_validate(hp_model, X,
                            Y,
                            cv=Auto.shape[0]) 
cv_err = np.mean(cv_results['test_score'])
cv_err

24.23151351792924

In [15]:
cv_error = np.zeros(5)
H = np.array(Auto['horsepower'])
M = sklearn_sm(sm.OLS)
for i, d in enumerate(range(1,6)):
    X = np.power.outer(H, np.arange(d+1)) 
    M_CV = cross_validate(M,X,Y,cv=Auto.shape[0])
    cv_error[i] = np.mean(M_CV['test_score']) 
cv_error

array([24.23151352, 19.24821312, 19.33498406, 19.42443035, 19.03323998])

In [16]:
# k-fold CV with k<n
cv_error = np.zeros(5) 
cv = KFold(n_splits=10,
                                  shuffle=True,
                                  random_state=0) # use same splits for each degree 
for i, d in enumerate(range(1,6)):
    X = np.power.outer(H, np.arange(d+1))
    M_CV = cross_validate(M,
                          X, 
                          Y,
                          cv=cv)
    cv_error[i] = np.mean(M_CV['test_score'])
cv_error

array([24.20766449, 19.18533142, 19.27626666, 19.47848399, 19.13719541])

In [17]:
# Using shufflesplit
validation = ShuffleSplit(n_splits=1, test_size=196,
random_state=0) 
results = cross_validate(hp_model,Auto.drop(['mpg'], axis=1), Auto['mpg'], cv=validation)
results['test_score']

array([23.61661707])

In [18]:
validation = ShuffleSplit(n_splits=10, test_size=196,random_state=0) 
results = cross_validate(hp_model, Auto.drop(['mpg'], axis=1), Auto['mpg'],
                         cv=validation)
results['test_score'].mean(), results['test_score'].std()

(23.802232661034168, 1.4218450941091838)

Note that this standard deviation is not a valid estimate of the sam- pling variability of the mean test score or the individual scores, since the randomly-selected training samples overlap and hence introduce correla- tions.

### 5.3.3 The Booststrap

    Can be applied in almost all situations with no complicated mathematical calculations are required.

In [20]:
Portfolio = load_data("Portfolio")
# This function return estimate alpha for the problem above
def alpha_func(D, idx):
    cov_ = np.cov(D[['X','Y']].loc[idx], rowvar=False) 
    return ((cov_[1,1] - cov_[0,1]) /
    (cov_[0,0]+cov_[1,1]-2*cov_[0,1]))
alpha_func(Portfolio, range(100))

0.57583207459283

In [21]:
rng = np.random.default_rng(0) 
alpha_func(Portfolio,
rng.choice(100, 100,
replace=True))

0.6074452469619002

In [23]:
def boot_SE(func, D,n=None, B=1000, seed=0):
    rng = np.random.default_rng(seed) 
    first_ , second_ = 0, 0
    n = n or D.shape[0]
    for _ in range(B):
        idx = rng.choice(D.index,
        n,
        replace=True) 
        value = func(D, idx)
        first_ += value
        second_ += value**2
    return np.sqrt(second_ / B - (first_ / B)**2)

In [24]:
alpha_SE = boot_SE(alpha_func, Portfolio ,B=1000, seed=0)
alpha_SE

0.09118176521277516

### Estimating the Accuracy of a Liear Regression Model
We can use bootstrap method to assess the variability of the coefficient estimates and predictions from a statistical learning method.

In [25]:

def boot_OLS(model_matrix, response, D, idx): 
    D_ = D.loc[idx]
    Y_ = D_[response]
    X_ = clone(model_matrix).fit_transform(D_) 
    return sm.OLS(Y_, X_).fit().params

In [28]:
hp_func= partial(boot_OLS,MS(['horsepower']),'mpg')

    The partial function take a function as an argument and freeze some of the arguments of the function

In [29]:
rng = np.random.default_rng(0) 
np.array([hp_func(Auto,rng.choice(392,
                                  392,
                                  replace=True)) for _ in range(10)])

array([[39.88064456, -0.1567849 ],
       [38.73298691, -0.14699495],
       [38.31734657, -0.14442683],
       [39.91446826, -0.15782234],
       [39.43349349, -0.15072702],
       [40.36629857, -0.15912217],
       [39.62334517, -0.15449117],
       [39.0580588 , -0.14952908],
       [38.66688437, -0.14521037],
       [39.64280792, -0.15555698]])

In [31]:
hp_se = boot_SE(hp_func, Auto ,B=1000,seed=10)
hp_se

intercept     0.848807
horsepower    0.007352
dtype: float64

The difference between the se of the bootstrap and the se in the model may stem from the fact that our model made several assumption while the bootstrap method does not.